In [1]:
import numpy as np
import pandas as pd

# Student Data

In [2]:
# 0. Student Dataset
student_data = pd.DataFrame({"Name":["Praveen","Vidhya","Dravis","Dennis","Sunder","Bharati"],
                            "subA":[55,98,8,52,99,87],
                            "subB":[80,95,18,46,100,44],
                            "subC":[12,94,5,89,85,55],
                            "subD":[55,95,12,89,100,78],
                            "subE":[88,99,15,99,99,88]}
                           )
student_data.set_index('Name',inplace=True)
student_data

subA  subB  subC  subD  subE
Name                                 
Praveen    55    80    12    55    88
Vidhya     98    95    94    95    99
Dravis      8    18     5    12    15
Dennis     52    46    89    89    99
Sunder     99   100    85   100    99
Bharati    87    44    55    78    88

In [3]:
names = ["Praveen","Vidhya","Dravis","Dennis","Sunder","Bharati"]

In [4]:
students = student_data.values
students

array([[ 55,  80,  12,  55,  88],
       [ 98,  95,  94,  95,  99],
       [  8,  18,   5,  12,  15],
       [ 52,  46,  89,  89,  99],
       [ 99, 100,  85, 100,  99],
       [ 87,  44,  55,  78,  88]], dtype=int64)

In [5]:
# 1. Maximum marks scored in subC
maxC = students.argmax(axis=0)[2]
print(f"{names[maxC]} got {students[maxC][2]}")

Vidhya got 94


In [6]:
# 2. Average marks in subE
meanE = students.mean(axis=0)[4]
print(f"Mean of subE is {meanE}")

Mean of subE is 81.33333333333333


In [7]:
# 3. Average marks scored by Dennis
avgDennis = students[3].mean()
print(f'Average marks scored by Dennis is {avgDennis}')

Average marks scored by Dennis is 75.0


In [8]:
# 4. Topper of class
total_of_students = students.sum(axis=1)
topper = names[total_of_students.argmax()]
topper_marks = total_of_students.max()
print(f"Topper is {topper} with {topper_marks} marks")

Topper is Sunder with 483 marks


In [9]:
# 5. Person who scored maximum marks in Sub B
maxC = students.argmax(axis=0)[1]
print(f"{names[maxC]} got {students[maxC][1]}")

Sunder got 100


# Question 2

In [10]:
# 1. Create Sample array
sample_array = np.array([0,1,2,3,4,5]) + np.array([[0],
                                                  [10],
                                                  [20],
                                                  [30],
                                                  [40],
                                                  [50]])
sample_array

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [11]:
# 2. Extract 3rd column 
sample_array[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [12]:
# 3. Extract [3,4]
sample_array[0][3:5]

array([3, 4])

In [13]:
# 4. Extract [20,22,24,40,42,44]
sample_array[2::2,0::2].reshape(6,)

array([20, 22, 24, 40, 42, 44])

In [14]:
# 5. Extract [44,45,54,55]
sample_array[-2:,-2:].reshape(4,)

array([44, 45, 54, 55])

# Question 3 

### Create an array

In [15]:
base = np.zeros((5,5),dtype='int')
base.fill(100)
base[1:4,1:4].fill(50)
base[2,2] = 0
base

array([[100, 100, 100, 100, 100],
       [100,  50,  50,  50, 100],
       [100,  50,   0,  50, 100],
       [100,  50,  50,  50, 100],
       [100, 100, 100, 100, 100]])